#pragma once

#define IDI_ICON1 101

#define IDR_FONT_IBM_PLEX_MONO_MEDIUM 201
#define IDR_FONT_IBM_PLEX_MONO_LIGHT 202
#define IDR_FONT_AWESOME_SOLID 203

#define IDR_LUT_RESYNE_DISPLAY_V1 301

#define IDR_FFMPEG_BINARY 401
