if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.12)
    cmake_policy(SET CMP0074 NEW)
endif()
if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.5)
    set(CMAKE_POLICY_DEFAULT_CMP0048 NEW)
endif()

include(cmake/vendor.cmake)

if(EXISTS "${GLFW_DIR}/CMakeLists.txt")
    message(STATUS "Using vendor GLFW from ${GLFW_DIR}")
    add_vendor_subdirectory(${GLFW_DIR} glfw)
    set(GLFW_TARGET glfw)
endif()

if(EXISTS "${JSON_DIR}/CMakeLists.txt")
    message(STATUS "Using vendor nlohmann/json from ${JSON_DIR}")
    add_vendor_subdirectory(${JSON_DIR} nlohmann_json)
endif()

if(EXISTS "${PORTAUDIO_DIR}/CMakeLists.txt")
    message(STATUS "Using vendor PortAudio from ${PORTAUDIO_DIR}")

    set(CMAKE_POLICY_VERSION_MINIMUM 3.5 CACHE STRING "Minimum policy version for CMake" FORCE)

    add_vendor_subdirectory(${PORTAUDIO_DIR} portaudio)
    if(TARGET PortAudio::PortAudio)
        set(PORTAUDIO_TARGET PortAudio::PortAudio)
    elseif(TARGET portaudio)
        set(PORTAUDIO_TARGET portaudio)
    else()
        message(FATAL_ERROR "PortAudio target not found in ${PORTAUDIO_DIR}")
    endif()
endif()

if(ENABLE_MIDI AND EXISTS "${RTMIDI_DIR}/CMakeLists.txt")
    message(STATUS "Using vendor RtMidi from ${RTMIDI_DIR}")
    add_vendor_subdirectory(${RTMIDI_DIR} rtmidi)
    if(TARGET rtmidi)
        set(RTMIDI_TARGET rtmidi)
    else()
        message(WARNING "RtMidi target not found in ${RTMIDI_DIR}, MIDI support will be disabled")
        set(ENABLE_MIDI OFF)
    endif()
endif()

if(EXISTS "${BGFX_CMAKE_DIR}/CMakeLists.txt")
    message(STATUS "Using vendor bgfx via ${BGFX_CMAKE_DIR}")
    set(BX_DIR "${BX_DIR}" CACHE STRING "Location of bx." FORCE)
    set(BIMG_DIR "${BIMG_DIR}" CACHE STRING "Location of bimg." FORCE)
    set(BGFX_DIR "${BGFX_DIR}" CACHE STRING "Location of bgfx." FORCE)
    set(BGFX_BUILD_TOOLS ON CACHE BOOL "Build bgfx tools." FORCE)
    set(BGFX_BUILD_TOOLS_BIN2C OFF CACHE BOOL "Build bx binary-to-C tool." FORCE)
    set(BGFX_BUILD_TOOLS_SHADER ON CACHE BOOL "Build bgfx shader tool." FORCE)
    set(BGFX_BUILD_TOOLS_GEOMETRY OFF CACHE BOOL "Build bgfx geometry tools." FORCE)
    set(BGFX_BUILD_TOOLS_TEXTURE OFF CACHE BOOL "Build bgfx texture tools." FORCE)
    set(BGFX_BUILD_EXAMPLES OFF CACHE BOOL "Build bgfx examples." FORCE)
    set(BGFX_BUILD_EXAMPLE_COMMON OFF CACHE BOOL "Build bgfx example common." FORCE)
    set(BGFX_BUILD_TESTS OFF CACHE BOOL "Build bgfx tests." FORCE)
    set(BGFX_INSTALL OFF CACHE BOOL "Install bgfx targets." FORCE)
    set(BGFX_CUSTOM_TARGETS OFF CACHE BOOL "Include bgfx convenience targets." FORCE)
    add_vendor_subdirectory(${BGFX_CMAKE_DIR} bgfx)
    include(${BGFX_CMAKE_DIR}/cmake/bgfxToolUtils.cmake)
else()
    message(FATAL_ERROR "bgfx.cmake not found at ${BGFX_CMAKE_DIR}. Initialise submodules before configuring.")
endif()

if(UNIX AND NOT APPLE)
    find_package(ALSA REQUIRED)
    message(STATUS "Found ALSA: ${ALSA_LIBRARIES}")
endif()
